### ISSUE TITLE
[ValueBar] paints Negative Value 

### ISSUE THREAD

**Issue by Afroz-Shaikh** [GeekyAnts/GaugesFlutter#109]
BUG: `ValueBar` paints inside negative value , When no `value` is passed till default `value 0`

<img width="1439" alt="Screenshot 2023-03-17 at 2 54 49 PM" src="https://user-images.githubusercontent.com/50929682/225865058-3c874506-b886-43c6-9d04-dbe719a8835e.png">

### Description: When `start` Value is negative and  `end` value is greater than 0. The `ValueBar` is Filled until 0.
Steps to Reproduce:
```Dart
LinearGauge(
        // No Value is Passed
          start: -50,
          end: 50,
          gaugeOrientation: GaugeOrientation.vertical,
          rulers: const RulerStyle(
            rulersOffset: 10,
            labelOffset: 10,
            inverseRulers: false,
            rulerPosition: RulerPosition.center,
            showLabel: true,
          ),
        ),
```
### Environment:
Version : `0.1`

### Proposed Solution
>The `ValueBar` takes 0 as its default value and hence when no value is passed it paints until 0. 

Assign `start` value as the default value of the `LinearGauge`

### Additonal Information

- This issue occurs in both GaugeOrientations
- The issue occurs consistently across different devices and browsers.

**Comment by Afroz-Shaikh** [comment]
## Issue Persits for `RangeLinearGauge` also such that `ValueBar` Draws under `RangeLinearGauge`

<img width="797" alt="Screenshot 2023-03-17 at 3 11 55 PM" src="https://user-images.githubusercontent.com/50929682/225869009-7ca9951a-db7e-460a-ad20-2afbcce11185.png">

## Steps to Reproduce:
```Dart
  child: LinearGauge(
          start: -50,
          end: 0,
          gaugeOrientation: GaugeOrientation.horizontal,
          rangeLinearGauge: [
            RangeLinearGauge(color: Colors.red, start: -50, end: -35),
            RangeLinearGauge(color: Colors.green, start: -15, end: 0)
          ],
          rulers: const RulerStyle(
            rulersOffset: 10,
            labelOffset: 10,
            inverseRulers: false,
            rulerPosition: RulerPosition.center,
            showLabel: true,
          ),
        ),
```

**Comment by SahilSharma2710** [comment]
May be it’s because value of valueBar is 0 , when value of valueBar -50 it will run fine !
