### ISSUE TITLE
[CustomLabels] : CustomLabels Throws Error When Single Label Passed at 0 value

### ISSUE THREAD

**Issue by Afroz-Shaikh** [GeekyAnts/GaugesFlutter#116]
## BUG:  `CustomLabels` Throws Error When Single `customLabel` is passed at 0 value
<img width="728" alt="Screenshot 2023-03-20 at 12 14 34 PM" src="https://user-images.githubusercontent.com/50929682/226266137-0972ea26-dcd7-4cc6-8fe4-feb773a444d8.png">

### Steps to Reproduce:
```Dart
LinearGauge(
          start: 0,
          end: 100,
          customLabels: [CustomRulerLabel(text: "Custom", value: 0)],
          rulers: RulerStyle(rulerPosition: RulerPosition.bottom),
        ),
```

### Environment:
Version : `0.1`

### Additonal Information

- This issue occurs in both GaugeOrientations
- The issue occurs consistently across different devices and browsers.

**Comment by hasnentai** [comment]
I guess we should have a proper `assert` for this which should say that we need at least 2 labels.
