### ISSUE TITLE
[RangeLinearGauge] : RangeLinearGauge Fails when RulerPosition is Top 

### ISSUE THREAD

**Issue by Afroz-Shaikh** [GeekyAnts/GaugesFlutter#150]
## BUG:  `RangeLinearGauge` renders incorrectly when `rulerPosition` is top.
<img width="1440" alt="Screenshot 2023-03-24 at 7 33 51 PM" src="https://user-images.githubusercontent.com/50929682/227543125-5293a44f-7e27-4a32-b6d6-873d32b2474a.png">

### Steps to Reproduce:
```Dart
LinearGauge(
        gaugeOrientation: GaugeOrientation.horizontal,
        rangeLinearGauge: [
          RangeLinearGauge(color: Colors.green, start: 0, end: 50),
          RangeLinearGauge(color: Colors.yellow, start: 50, end: 75),
          RangeLinearGauge(color: Colors.red, start: 75, end: 100),
        ],
        rulers: const RulerStyle(
          rulerPosition: RulerPosition.top,
        ),
      )
```

### Additonal Information

- This issue occurs in only Horizontal Orientation 
- The issue occurs consistently across different devices and browsers.

**Comment by Afroz-Shaikh** [comment]
After  ViewBox change, we don't need to `size.height - offset.dy - getThickness` as the RangeLinearGauge aligns Correctly

**Comment by hasnentai** [comment]
Can you quote the GitHub hub file with a line ? Where exactly the condition is ?

**Comment by Afroz-Shaikh** [comment]
File : `linear_gauge_painter.dart` Line no: 981
