### ISSUE TITLE
Possibility to customize the label of the radial track

### ISSUE THREAD

**Issue by LudoPL** [GeekyAnts/GaugesFlutter#245]
***I would like to display "$10" instead of "10.0" on the label of the radial track***
Currently, labels on the radial track are for example "10.0", "20.0", "30.0", and I would like them to be for example "$10", "$20", etc
It seems there is currently no way to change how these labels are displayed.

***Add a RadialTrack constructor argument to convert double track number to string label***
It would be great if the RadialTrack constructor accept a function `String Function(double) mapTrackLabel` as argument.
Then, when drawing the label, instead of calling `exactValue.toString()`, `mapTrackLabel(exactValue)` may be called.
The default value for `mapTrackLabel` may be `(double value) => value.toString()` to keep current behavior.

Thanks for your great flutter gauge indicator !!

**Comment by LudoPL** [comment]
I have done a PR to try to implement that here : https://github.com/GeekyAnts/GaugesFlutter/pull/246

**Comment by Huascar321** [comment]
Hello everyone, any news about this? This is feature is exactly what I'm looking for.

**Comment by PushBackNeil** [comment]
Hi, is this feature available in geekyants_flutter_gauges: 1.0.1?

**Comment by hasnentai** [comment]
Hi @LudoPL 
I have merged your PR in the development branch and it can be used as a workaround. 

Usage in pubspec.yaml

```yaml
geekyants_flutter_gauges:
   git:
      url: 'https://github.com/GeekyAnts/GaugesFlutter.git'
      ref:development
```

cc : @PushBackNeil @Huascar321 @Afroz-Shaikh

**Comment by hackengineer** [comment]
We would like to use this feature as decimal points take up too much space on our dashboard (0 - 8000 RPM).  Can we get this released so we don't have to use a development branch in production?

**Comment by Afroz-Shaikh** [comment]
> We would like to use this feature as decimal points take up too much space on our dashboard (0 - 8000 RPM).  Can we get this released so we don't have to use a development branch in production?

Hey will deploy a new release soon with this feature included

**Comment by Afroz-Shaikh** [comment]
This feature is live on [1.0.4](https://pub.dev/packages/geekyants_flutter_gauges) 
cc: @hackengineer @Huascar321 @LudoPL
